services:
  db:
    image: postgres:17.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - full-stack-starter
  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - full-stack-starter
  storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: minio server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    networks:
      - full-stack-starter
  storage-setup:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      mc alias set myminio http://storage:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/app;
      exit 0;
      "
    networks:
      - full-stack-starter
networks:
  full-stack-starter:
    name: full-stack-starter
    driver: bridge
