name: CI
on: 
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:22.13.1-bookworm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Generate Prisma client
        run: cd server && npx prisma generate
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests
        run: cp server/example.env server/.env && npm test
